spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
    suffix: .html
  datasource:
       driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
       url: jdbc:sqlserver://P3TWSQL02\PSQL;databaseName=gdMasterCatalog;integratedSecurity=true;

server:
  port: 8081
